# Demo prometheus Config file

global:
  scrape_interval:     7s 
  evaluation_interval: 7s 

scrape_configs:
  - job_name: 'prometheus'
    static_configs:
    - targets: ['localhost:9090']

  - job_name: 'Docker-monitor'
    static_configs:
    - targets: ['ec2-18-222-143-112.us-east-2.compute.amazonaws.com:9091']

  - job_name: 'cAdvisor-Monitor-ByHostName'
    static_configs:
    - targets: ['ec2-18-222-143-112.us-east-2.compute.amazonaws.com:8080']

  - job_name: 'cAdvisor-Monitor-ByContainerName'
    static_configs:
    - targets: ['cadvisor:8080']

